### ISSUE TITLE
sbank v1.0.0 date format issue

### ISSUE THREAD

**Issue by MariaAssiduo** [gwastro/sbank#36]
Hello. I have used git clone to install the latest sbank version 1.0.0 in my CIT directory /home/maria.assiduo/gwastro6/

Using it to build a tamplates bank, this error occurred:

```
Traceback (most recent call last):
  File "/home/maria.assiduo/gwastro6/sbank_Python3/bin/sbank", line 461, in <module>
    process = ligolw_process.register_to_xmldoc(xmldoc, "sbank",
  File "/home/maria.assiduo/gwastro6/sbank_Python3/lib/python3.9/site-packages/ligo/lw/utils/process.py", line 100, in register_to_xmldoc
    process = proctable.RowType.initialized(program = program, process_id = proctable.get_next_id(), **kwargs)
  File "/home/maria.assiduo/gwastro6/sbank_Python3/lib/python3.9/site-packages/ligo/lw/lsctables.py", line 586, in initialized
    cvs_entry_time = lal.UTCToGPS(time.strptime(cvs_entry_time, "%Y-%m-%d %H:%M:%S +0000")) if cvs_entry_time is not None else None,
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-20211019/lib/python3.9/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-20211019/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-01-23 10:19:14 +000' does not match format '%Y-%m-%d %H:%M:%S +0000'
```

I tried to modify the line 463 in /home/maria.assiduo/gwastro6/sbank_Python3/bin/sbank in this way:

cvs_repository="sbank", cvs_entry_time=strftime('%Y-%m-%d %H:%M:%S +000'))   //wrong

cvs_repository="sbank", cvs_entry_time=strftime('%Y-%m-%d %H:%M:%S +0000'))  //corrected to match line 586  cvs_entry_time = lal.UTCToGPS(time.strptime(cvs_entry_time, "%Y-%m-%d %H:%M:%S +0000")) in  -> /home/maria.assiduo/gwastro6/sbank_Python3/lib/python3.9/site-packages/ligo/lw/lsctables.py 

After the modification, I upgrade sbank with the command line " pip install . " in /home/maria.assiduo/gwastro6/sbank , but nothing changed. The line 463 in  /home/maria.assiduo/gwastro6/sbank_Python3/bin/sbank still appear with the initial error

cvs_repository="sbank", cvs_entry_time=strftime('%Y-%m-%d %H:%M:%S +000')).

Any suggestion?

Thank you in advance.

**Comment by spxiwh** [comment]
@MariaAssiduo Thanks for reporting this, this does mean that the v1.0.0 release is broken (and I need to write some better unittests!). I don't understand why this wasn't an issue before though, I guess it's part of the ligo.lw transition. The fix is what you suggest, and I'll get this onto here now.

I'm not sure why the steps you mention don't fix the problem. Perhaps try `pip uninstall pycbc` before `pip install .` to make sure the old files get removed. Otherwise you could just edit `/home/maria.assiduo/gwastro6/sbank_Python3/bin/sbank` directly to change this.

**Comment by MariaAssiduo** [comment]
@spxiwh I am sorry, but do you mean "pip uninstall sbank" despite pycbc? if so, in this way will I lose the modifications I did in the scripts waveforms.py and tau0tau3.py in /home/maria.assiduo/gwastro6/sbank/sbank/?

About the suggestion to simply edit /home/maria.assiduo/gwastro6/sbank_Python3/bin/sbank and correct the line, I tried already, I get this error:
```
Traceback (most recent call last):
  File "/home/maria.assiduo/gwastro6/sbank_Python3/bin/sbank", line 592, in <module>
    ligolw_process.set_process_end_time(process)
AttributeError: module 'ligo.lw.utils.process' has no attribute 'set_process_end_time'
```
Thank you in advance.

**Comment by spxiwh** [comment]
@MariaAssiduo If editing the file directly works, then I would stick with that (I did mean `pip uninstall sbank` not `pip uninstall pycbc` though! Doing this uninstall should also not remove stuff in the source directory (but always a good idea to back up changes using github)).

I also encountered the second error while investigating this yesterday. If you look at the patch I'm proposing here:

https://github.com/gwastro/sbank/pull/37/files

You can see I've changed:

```
ligolw_process.set_process_end_time(process)
```

to

```
process.set_end_time_now()
```

in the two places it appears. (This seems to have been a change from the latest version of ligo.lw).

**Comment by MariaAssiduo** [comment]
@spxiwh Hi, with the last changes I was able to run sbank normally and build a template bank. Thank you

**Comment by spxiwh** [comment]
Thanks @MariaAssiduo. Good to hear that this worked!
